# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: ebussola.feedback::lang.channel.one

# Model Form Field configuration
form: $/ebussola/feedback/models/channel/fields.yaml

# Model Class name
modelClass: eBussola\Feedback\Models\Channel

# Default redirect location
defaultRedirect: ebussola/feedback/channels

# Create page
create:
    title: ebussola.feedback::lang.channel.action.create
    redirect: ebussola/feedback/channels/update/:id
    redirectClose: ebussola/feedback/channels

# Update page
update:
    title: ebussola.feedback::lang.channel.action.update
    redirect: ebussola/feedback/channels
    redirectClose: ebussola/feedback/channels

# Preview page
preview:
    title: ebussola.feedback::lang.channel.action.preview
